global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'chat-app'
    static_configs:
      - targets: ['172.17.0.1:8000']  # Docker bridge network IP
        labels:
          app: 'chat-app'
          environment: 'local'
